# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Heart Disease Prediction Task
author: Anthony Reidy
logo: images/heart_disease.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 5000

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: Anthony_Reidy.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _bibliography/references.bib

# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Information about where the book exists on the web
repository:
  url: https://github.optum.com/areidy1/learn-hub/tree/main/Anthony/heart_disease_task  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
